"""empty message

Revision ID: 2a798695be49
Revises: 62582649ce6e
Create Date: 2016-07-20 15:28:26.656538

"""

# revision identifiers, used by Alembic.
revision = '2a798695be49'
down_revision = '62582649ce6e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('append', sa.Column('append_deleted', sa.Boolean(), nullable=True))
    op.add_column('append', sa.Column('topic_deleted', sa.Boolean(), nullable=True))
    op.drop_column('append', 'deleted')
    op.add_column('comment', sa.Column('comment_deleted', sa.Boolean(), nullable=True))
    op.add_column('comment', sa.Column('topic_deleted', sa.Boolean(), nullable=True))
    op.drop_column('comment', 'deleted')
    op.add_column('notify', sa.Column('comment_deleted', sa.Boolean(), nullable=True))
    op.add_column('notify', sa.Column('receiver_deleted', sa.Boolean(), nullable=True))
    op.add_column('notify', sa.Column('sender_deleted', sa.Boolean(), nullable=True))
    op.add_column('notify', sa.Column('topic_deleted', sa.Boolean(), nullable=True))
    op.add_column('topic', sa.Column('node_deleted', sa.Boolean(), nullable=True))
    op.add_column('topic', sa.Column('topic_deleted', sa.Boolean(), nullable=True))
    op.add_column('topic', sa.Column('user_deleted', sa.Boolean(), nullable=True))
    op.drop_column('topic', 'deleted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('topic', 'user_deleted')
    op.drop_column('topic', 'topic_deleted')
    op.drop_column('topic', 'node_deleted')
    op.drop_column('notify', 'topic_deleted')
    op.drop_column('notify', 'sender_deleted')
    op.drop_column('notify', 'receiver_deleted')
    op.drop_column('notify', 'comment_deleted')
    op.add_column('comment', sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('comment', 'topic_deleted')
    op.drop_column('comment', 'comment_deleted')
    op.add_column('append', sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('append', 'topic_deleted')
    op.drop_column('append', 'append_deleted')
    ### end Alembic commands ###
