"""empty message

Revision ID: 2b5859bebcf1
Revises: 39c00b1bb40c
Create Date: 2016-07-13 20:09:15.415683

"""

# revision identifiers, used by Alembic.
revision = '2b5859bebcf1'
down_revision = '39c00b1bb40c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notify', 'is_read')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notify', sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
