"""empty message

Revision ID: 3420f22521af
Revises: 2a798695be49
Create Date: 2016-07-22 20:11:58.546191

"""

# revision identifiers, used by Alembic.
revision = '3420f22521af'
down_revision = '2a798695be49'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_deleted', sa.Boolean(), nullable=True))
    op.add_column('notify', sa.Column('append_deleted', sa.Boolean(), nullable=True))
    op.drop_column('notify', 'receiver_deleted')
    op.drop_column('notify', 'sender_deleted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notify', sa.Column('sender_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('notify', sa.Column('receiver_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('notify', 'append_deleted')
    op.drop_column('comment', 'user_deleted')
    ### end Alembic commands ###
