"""empty message

Revision ID: 39c00b1bb40c
Revises: 59e062953154
Create Date: 2016-07-13 19:30:30.469749

"""

# revision identifiers, used by Alembic.
revision = '39c00b1bb40c'
down_revision = '59e062953154'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notify', 'content')
    op.drop_column('users', 'use_avatar')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('use_avatar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('notify', sa.Column('content', mysql.TEXT(), nullable=True))
    ### end Alembic commands ###
