"""empty message

Revision ID: 59e062953154
Revises: fb71a8f269d8
Create Date: 2016-07-05 22:25:34.763623

"""

# revision identifiers, used by Alembic.
revision = '59e062953154'
down_revision = 'fb71a8f269d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_password_reset_link_valid', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_password_reset_link_valid')
    ### end Alembic commands ###
