"""empty message

Revision ID: 62582649ce6e
Revises: c02c89e63a71
Create Date: 2016-07-20 09:11:58.066988

"""

# revision identifiers, used by Alembic.
revision = '62582649ce6e'
down_revision = 'c02c89e63a71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'deleted')
    ### end Alembic commands ###
