"""empty message

Revision ID: 8e75c327e44f
Revises: 2b5859bebcf1
Create Date: 2016-07-14 12:11:38.471105

"""

# revision identifiers, used by Alembic.
revision = '8e75c327e44f'
down_revision = '2b5859bebcf1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True))
    ### end Alembic commands ###
