"""empty message

Revision ID: fb71a8f269d8
Revises: 83fd966f85c2
Create Date: 2016-07-03 14:05:09.827816

"""

# revision identifiers, used by Alembic.
revision = 'fb71a8f269d8'
down_revision = '83fd966f85c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('topics', sa.Text(), nullable=True))
    op.add_column('topic', sa.Column('appends', sa.Text(), nullable=True))
    op.add_column('topic', sa.Column('comments', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('comments', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('read_notify', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('topics', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('unread_notify', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unread_notify')
    op.drop_column('users', 'topics')
    op.drop_column('users', 'read_notify')
    op.drop_column('users', 'comments')
    op.drop_column('topic', 'comments')
    op.drop_column('topic', 'appends')
    op.drop_column('node', 'topics')
    ### end Alembic commands ###
